[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kaggle_lib"
version = "0.1.1"
description = "Helper functions for data processing and Colab integration"
authors = [{name = "Fabrizio Basso"}]
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn>=0.13.0",
]

[tool.setuptools]
packages = ["kaggle_lib"]
